service:
  name: snuboard
plugins:
  - serverless-dynamodb-local
  - serverless-webpack
  - serverless-offline
  # - serverless-domain-manager
  - serverless-prune-plugin
custom:
  serverless-offline:
    httpPort: 9000
    lambdaPort: 9002
  webpack:
    includeModules: true
    packager: 'yarn'
    keepOutputDirectory: true
  prune:
    automatic: true
    number: 3
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      migrate: true
  tables:
    board: 'board-${opt:stage}'
    notice: 'notice-${opt:stage}'
    department: 'department-${opt:stage}'
  # domain: ${file(resources/domain.yml)}
  # customDomain:
  #   rest:
  #     domainName: ${self:custom.domain.apiUrl}
  #     stage: ${opt:stage}
  #     basePath: ${opt:stage}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: ap-northeast-2
  environment:
    # HTTP_ENDPOINT:
    #   {
    #     'Fn::Join':
    #       [
    #         '',
    #         [
    #           'https://',
    #           { 'Ref': 'ApiGatewayRestApi' },
    #           '.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}',
    #         ],
    #       ],
    #   }
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    # Ports for dev
    DEV_HTTP_PORT: ${self:custom.serverless-offline.httpPort}
    DEV_LAMBDA_PORT: ${self:custom.serverless-offline.lambdaPort}
    # DynamoDB Table Names
    NOTICE_TABLE: ${self:custom.tables.notice}
    DEPARTMENT_TABLE: ${self:custom.tables.department}
    BOARD_TABLE: ${self:custom.tables.board}
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - Fn::Join:
            - ':'
            - - arn:aws:lambda
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - function:*
functions:
  # --- http ---

  # --- scheduled ---
  crawl:
    handler: src/crawler/crawl.handler
    timeout: 60
    memorySize: 512
    events:
      - schedule:
          rate: cron(0 10 * * ? *)
          enabled: true

resources:
  - ${file(resources/dynamodb.yml)}
